SslPolicies:
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 5
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 9
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 12
  - Name: AES128-GCM-SHA256
    Priority: 13
  - Name: AES128-SHA256
    Priority: 14
  - Name: AES128-SHA
    Priority: 15
  - Name: AES256-GCM-SHA384
    Priority: 16
  - Name: AES256-SHA256
    Priority: 17
  - Name: AES256-SHA
    Priority: 18
  Name: ELBSecurityPolicy-2016-08
  SslProtocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: TLS_AES_128_GCM_SHA256
    Priority: 1
  - Name: TLS_AES_256_GCM_SHA384
    Priority: 2
  - Name: TLS_CHACHA20_POLY1305_SHA256
    Priority: 3
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 4
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 5
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 6
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 7
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 9
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 11
  Name: ELBSecurityPolicy-TLS13-1-2-2021-06
  SslProtocols:
  - TLSv1.2
  - TLSv1.3
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: TLS_AES_128_GCM_SHA256
    Priority: 1
  - Name: TLS_AES_256_GCM_SHA384
    Priority: 2
  - Name: TLS_CHACHA20_POLY1305_SHA256
    Priority: 3
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 4
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 5
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 6
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 7
  Name: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
  SslProtocols:
  - TLSv1.2
  - TLSv1.3
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: TLS_AES_128_GCM_SHA256
    Priority: 1
  - Name: TLS_AES_256_GCM_SHA384
    Priority: 2
  - Name: TLS_CHACHA20_POLY1305_SHA256
    Priority: 3
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 4
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 5
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 6
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 7
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 9
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 11
  - Name: AES128-GCM-SHA256
    Priority: 12
  - Name: AES128-SHA256
    Priority: 13
  - Name: AES256-GCM-SHA384
    Priority: 14
  - Name: AES256-SHA256
    Priority: 15
  Name: ELBSecurityPolicy-TLS13-1-2-Ext1-2021-06
  SslProtocols:
  - TLSv1.2
  - TLSv1.3
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: TLS_AES_128_GCM_SHA256
    Priority: 1
  - Name: TLS_AES_256_GCM_SHA384
    Priority: 2
  - Name: TLS_CHACHA20_POLY1305_SHA256
    Priority: 3
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 4
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 5
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 6
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 7
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 8
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 9
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 12
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 13
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 14
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 15
  - Name: AES128-GCM-SHA256
    Priority: 16
  - Name: AES128-SHA256
    Priority: 17
  - Name: AES128-SHA
    Priority: 18
  - Name: AES256-GCM-SHA384
    Priority: 19
  - Name: AES256-SHA256
    Priority: 20
  - Name: AES256-SHA
    Priority: 21
  Name: ELBSecurityPolicy-TLS13-1-2-Ext2-2021-06
  SslProtocols:
  - TLSv1.2
  - TLSv1.3
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: TLS_AES_128_GCM_SHA256
    Priority: 1
  - Name: TLS_AES_256_GCM_SHA384
    Priority: 2
  - Name: TLS_CHACHA20_POLY1305_SHA256
    Priority: 3
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 4
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 5
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 6
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 7
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 8
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 9
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 12
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 13
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 14
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 15
  - Name: AES128-GCM-SHA256
    Priority: 16
  - Name: AES128-SHA256
    Priority: 17
  - Name: AES128-SHA
    Priority: 18
  - Name: AES256-GCM-SHA384
    Priority: 19
  - Name: AES256-SHA256
    Priority: 20
  - Name: AES256-SHA
    Priority: 21
  Name: ELBSecurityPolicy-TLS13-1-1-2021-06
  SslProtocols:
  - TLSv1.1
  - TLSv1.2
  - TLSv1.3
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: TLS_AES_128_GCM_SHA256
    Priority: 1
  - Name: TLS_AES_256_GCM_SHA384
    Priority: 2
  - Name: TLS_CHACHA20_POLY1305_SHA256
    Priority: 3
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 4
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 5
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 6
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 7
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 8
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 9
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 12
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 13
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 14
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 15
  - Name: AES128-GCM-SHA256
    Priority: 16
  - Name: AES128-SHA256
    Priority: 17
  - Name: AES128-SHA
    Priority: 18
  - Name: AES256-GCM-SHA384
    Priority: 19
  - Name: AES256-SHA256
    Priority: 20
  - Name: AES256-SHA
    Priority: 21
  Name: ELBSecurityPolicy-TLS13-1-0-2021-06
  SslProtocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2
  - TLSv1.3
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: TLS_AES_128_GCM_SHA256
    Priority: 1
  - Name: TLS_AES_256_GCM_SHA384
    Priority: 2
  - Name: TLS_CHACHA20_POLY1305_SHA256
    Priority: 3
  Name: ELBSecurityPolicy-TLS13-1-3-2021-06
  SslProtocols:
  - TLSv1.3
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 5
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 8
  - Name: AES128-GCM-SHA256
    Priority: 9
  - Name: AES128-SHA256
    Priority: 10
  - Name: AES256-GCM-SHA384
    Priority: 11
  - Name: AES256-SHA256
    Priority: 12
  Name: ELBSecurityPolicy-TLS-1-2-2017-01
  SslProtocols:
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 5
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 9
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 12
  - Name: AES128-GCM-SHA256
    Priority: 13
  - Name: AES128-SHA256
    Priority: 14
  - Name: AES128-SHA
    Priority: 15
  - Name: AES256-GCM-SHA384
    Priority: 16
  - Name: AES256-SHA256
    Priority: 17
  - Name: AES256-SHA
    Priority: 18
  Name: ELBSecurityPolicy-TLS-1-1-2017-01
  SslProtocols:
  - TLSv1.1
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 5
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 9
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 12
  - Name: AES128-GCM-SHA256
    Priority: 13
  - Name: AES128-SHA256
    Priority: 14
  - Name: AES128-SHA
    Priority: 15
  - Name: AES256-GCM-SHA384
    Priority: 16
  - Name: AES256-SHA256
    Priority: 17
  - Name: AES256-SHA
    Priority: 18
  Name: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
  SslProtocols:
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 5
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 9
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 12
  Name: ELBSecurityPolicy-FS-2018-06
  SslProtocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 5
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 9
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 12
  - Name: AES128-GCM-SHA256
    Priority: 13
  - Name: AES128-SHA256
    Priority: 14
  - Name: AES128-SHA
    Priority: 15
  - Name: AES256-GCM-SHA384
    Priority: 16
  - Name: AES256-SHA256
    Priority: 17
  - Name: AES256-SHA
    Priority: 18
  Name: ELBSecurityPolicy-2015-05
  SslProtocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 5
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 9
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 12
  - Name: AES128-GCM-SHA256
    Priority: 13
  - Name: AES128-SHA256
    Priority: 14
  - Name: AES128-SHA
    Priority: 15
  - Name: AES256-GCM-SHA384
    Priority: 16
  - Name: AES256-SHA256
    Priority: 17
  - Name: AES256-SHA
    Priority: 18
  - Name: DES-CBC3-SHA
    Priority: 19
  Name: ELBSecurityPolicy-TLS-1-0-2015-04
  SslProtocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 5
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 8
  Name: ELBSecurityPolicy-FS-1-2-Res-2019-08
  SslProtocols:
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 5
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 9
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 12
  Name: ELBSecurityPolicy-FS-1-1-2019-08
  SslProtocols:
  - TLSv1.1
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES128-SHA256
    Priority: 3
  - Name: ECDHE-RSA-AES128-SHA256
    Priority: 4
  - Name: ECDHE-ECDSA-AES128-SHA
    Priority: 5
  - Name: ECDHE-RSA-AES128-SHA
    Priority: 6
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 7
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 8
  - Name: ECDHE-ECDSA-AES256-SHA384
    Priority: 9
  - Name: ECDHE-RSA-AES256-SHA384
    Priority: 10
  - Name: ECDHE-RSA-AES256-SHA
    Priority: 11
  - Name: ECDHE-ECDSA-AES256-SHA
    Priority: 12
  Name: ELBSecurityPolicy-FS-1-2-2019-08
  SslProtocols:
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
- Ciphers:
  - Name: ECDHE-ECDSA-AES128-GCM-SHA256
    Priority: 1
  - Name: ECDHE-RSA-AES128-GCM-SHA256
    Priority: 2
  - Name: ECDHE-ECDSA-AES256-GCM-SHA384
    Priority: 3
  - Name: ECDHE-RSA-AES256-GCM-SHA384
    Priority: 4
  Name: ELBSecurityPolicy-FS-1-2-Res-2020-10
  SslProtocols:
  - TLSv1.2
  SupportedLoadBalancerTypes:
  - application
  - network
