name: Overwrite some file

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: 'List Certificates'
        id: describe_cf
        uses: jahanarun/aws-cli-action@v1
        with:
         access-key-id: ${{ env.access-key-id }}
         secret-access-key: ${{ env.secret-access-key }}
         default-region: ${{ env.default-region }}
         sub-command:  acm list-certificates 

      - description: Just echo the output
        run: echo '${{ steps.describe_cf.outputs.result }}'

      - uses: actions/github-script@v6
         description: Parses the output of the aws-cli as a JSON
        env:
         DESCRIBE_CF: ${{ steps.describe_cf.outputs.result }}
        with:
        script: |
          const text = process.env.DESCRIBE_CF;
          const data = JSON.parse(text);

          let outputVariables = data.Stacks[0].Outputs.reduce(
          (obj, item) => Object.assign(obj, { [item.OutputKey]: item.OutputValue }),
          {}
          );
          return outputVariables;

          
          
      
