name: AWS Evidence Collection

on:
  workflow_dispatch:
  schedule:
    # Runs "At 12:00 on day-of-month 28."
    - cron: '0 12 28 * *'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
         
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
         
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
         version: 2     # default
         verbose: false # default
         arch: amd64    # allowed values: amd64, arm64
         rootdir: ""    # defaults to "PWD"
         workdir: ""    # defaults to "PWD/unfor19-awscli"

      - name: Prepare Environment
        id: prep
        run: /bin/bash scripts/prep.sh
        continue-on-error: false
      
      - name: List ACM Certificates
        run: /bin/bash scripts/list-certs.sh
        continue-on-error: false

      - name: NTP Clock Synchronization
        run: /bin/bash scripts/r1550_ntp.sh
        continue-on-error: true

      - name: List of RDS Snapshots
        run: /bin/bash scripts/RDS_snapshots.sh
        continue-on-error: false
              
      - name: Fetch configuration change history of a specific AWS RDS DB Instance [A-lign ID:P-20]
        run: /bin/bash scripts/p20_RDS-changehistory.sh
        continue-on-error: false      
              
      - name: Run Inspector Script
        run: /bin/bash ./inspector.sh
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"

               
#      - uses: github-actions-x/commit@v2.9
#       with:
#         github-token: ${{ secrets.GITHUB_TOKEN }}
#         push-branch: 'main'
#         force-add: 'true'

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
