name: AWS Evidence Collection

on:
  schedule:
    # Runs "At 12:00 on day-of-month 28."
    - cron: '0 12 28 * *'
 
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
         version: 2     # default
         verbose: false # default
         arch: amd64    # allowed values: amd64, arm64
         rootdir: ""    # defaults to "PWD"
         workdir: ""    # defaults to "PWD/unfor19-awscli"
      - run: aws ec2 describe-client-vpn-endpoints
        shell: bash

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: Remote Access/VPN_Config.json
          write-mode: overwrite
          contents: |
            console.log('some contents')
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          
          
